"""init

Revision ID: bd4626ca907d
Revises: 
Create Date: 2025-09-06 00:42:32.224074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd4626ca907d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_data_user_email'), table_name='auth_data')
    op.drop_table('auth_data')
    op.drop_index(op.f('ix_payment_user_payment_id'), table_name='payment_user')
    op.drop_table('payment_user')
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('card_number', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('second_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('creation_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('Создан', 'Оплачен', 'Отменен', name='payment_status_enum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('payment_id', name='payment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payment_user',
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], name=op.f('payment_user_payment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('payment_user_pkey'))
    )
    op.create_index(op.f('ix_payment_user_payment_id'), 'payment_user', ['payment_id'], unique=False)
    op.create_table('auth_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_data_pkey'))
    )
    op.create_index(op.f('ix_auth_data_user_email'), 'auth_data', ['user_email'], unique=True)
    # ### end Alembic commands ###
