from app.core.operations.db_operations import DBRepository


class DBBalanceRepository(DBRepository):
    async def create(self): ...

    async def get(self): ...

    async def update(self): ...

    async def delete(self): ...
