from app.core.db_operations import DBRepository


class DBPaymentRepository(DBRepository):
    async def create(self): ...

    async def get(self): ...

    async def update(self): ...

    async def delete(self): ...
